apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-micro-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-micro-service
  template:
    metadata:
      labels:
        app: k8-micro-service
    spec:
      containers:
        - name: k8-micro-service
          image: birfbkdstsbhbk/k8-micro-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080