apiVersion: v1
kind: Service
metadata:
  name: k8-micro-service
spec:
  type: NodePort
  selector:
    app: k8-micro-service
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31000